-- Role: pruebas
-- DROP ROLE IF EXISTS pruebas;

CREATE ROLE pruebas WITH
  LOGIN
  SUPERUSER
  INHERIT
  CREATEDB
  CREATEROLE
  REPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:RWwKw/8TOfQGTv7y+OZpFA==$Xt5a9f4d93P2UqWVc02gxxbI2XJGg21Z9NtYq6RFpd8=:gpphhFolpGKoyRPIvIdw1MGBfCSuc3v/j6A7QbTLnTo=';